spring.application.name=ecommerce-backend
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=${SQL_INIT_MODE:always}

app.jwt.secret=${JWT_SECRET:VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yRWNvbW1lcmNlQXBwbGljYXRpb24xMjM0NTY=}
app.jwt.expiration=${JWT_EXPIRATION:86400000}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://localhost,http://127.0.0.1}

springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.open-in-view=false
